sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  
after_success:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o showrss .
  - docker build -t teambrookie/showrss .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t teambrookie/showrss .;
    docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push teambrookie/showrss;
    fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    docker build -t teambrookie/showrss:$TRAVIS_BRANCH .;
    docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push teambrookie/showrss:$TRAVIS_BRANCH;
    fi